apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: lab4-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4-backend
  template:
    metadata:
      labels:
        app: lab4-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/pozitp/lab4-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/lab4db
            - name: SPRING_DATASOURCE_USERNAME
              value: lab4user
            - name: SPRING_DATASOURCE_PASSWORD
              value: lab4pass
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: lab4-backend-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app: lab4-backend
  ports:
    - port: 8080
      targetPort: 8080
