apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: lab4-pipeline-run-
spec:
  pipelineRef:
    name: lab4-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: ghcr-secret
